import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, getDocs, addDoc, updateDoc, deleteDoc, query, orderBy, where, serverTimestamp, Timestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app);
const $ = id => document.getElementById(id), views = [...document.querySelectorAll("[data-view]")];
let currentUser = null, currentRole = null, adminSection = "activities", editingId = null, registrationInProgress = false, currentMemberSection = null;
const config = {
  activities: { collection: "publicActivities", title: "Activités", singular: "activité" },
  classifieds: { collection: "classifieds", title: "Entre voisins", singular: "annonce" },
  aid: { collection: "aid", title: "Entraide", singular: "demande" },
  artisans: { collection: "artisans", title: "Artisans", singular: "artisan" },
  users: { collection: "users", title: "Adhérents", singular: "adhérent" }
};
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
const asDate = value => value?.toDate ? value.toDate() : new Date(value);
const formatDate = value => value && !Number.isNaN(asDate(value).getTime()) ? new Intl.DateTimeFormat("fr-FR", { weekday:"long", day:"numeric", month:"long" }).format(asDate(value)) : "";
const inputDate = value => { if (!value) return ""; const d = asDate(value); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10); };
document.querySelector(".public-hero .hero-copy p").textContent="L’espace réservé aux adhérents pour se rencontrer, s’entraider et partager. Retrouvez les prochaines activités de l’AGP, les annonces entre voisins et les contacts recommandés.";
document.querySelector(".public-intro h2").textContent="L’AGP, au service des résidents";
document.querySelector(".public-intro p").textContent="L’association favorise les rencontres, la convivialité et l’entraide au sein du Grand Pavois.";
document.querySelector('[data-view="join"] .content.block').innerHTML=`<span class="eyebrow">ADHÉSION 2026</span><h2>Rejoignez l’Association du Grand Pavois</h2><p class="join-lead">Participez à la vie du Grand Pavois, rencontrez vos voisins et profitez des activités et services réservés aux adhérents.</p><div class="membership-prices"><div><span>INDIVIDUELLE</span><b>20 €</b><small>pour une personne</small></div><div><span>COUPLE</span><b>25 €</b><small>pour deux personnes</small></div></div><a class="helloasso-button" href="https://www.helloasso.com/associations/association-du-grand-pavois/adhesions/bulletin-d-adhesion-2026" target="_blank" rel="noopener noreferrer"><span>Adhérer en ligne avec HelloAsso</span><small>Paiement sécurisé sur le site HelloAsso ↗</small></a><div class="access-after-membership"><h3>Vous êtes déjà adhérent ?</h3><p>Demandez votre accès personnel à l’application AGP & Vous. Votre compte sera activé après vérification par l’association.</p><button class="primary full" id="requestAccess">Demander mon accès adhérent</button><button class="secondary-action full" data-route="contact">Contacter l’AGP</button></div>`;

function route(name) { views.forEach(v => v.classList.toggle("active", v.dataset.view === name)); document.querySelectorAll(".bottom [data-route]").forEach(b => b.classList.toggle("active", b.dataset.route === name)); scrollTo({top:0,behavior:"smooth"}); }
function openLogin(){ $("loginModal").classList.add("open"); } function closeLogin(){ $("loginModal").classList.remove("open"); }
function openSignup(){ if(currentUser)return;$("signupMessage").textContent="";$("signupModal").classList.add("open"); } function closeSignup(){ $("signupModal").classList.remove("open"); }
function message(text, kind="success"){ const box=$("adminMessage"); box.textContent=text; box.className=`admin-message ${kind}`; box.hidden=false; setTimeout(()=>box.hidden=true,4500); }
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>route(b.dataset.route)); document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeLogin);
$("homeLogin").onclick=openLogin; $("authButton").onclick=()=>currentUser?route(currentRole==="admin"?"admin":"member"):openLogin();$("requestAccess").onclick=openSignup;document.querySelectorAll("[data-signup-close]").forEach(b=>b.onclick=closeSignup);
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").textContent="";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);closeLogin();}catch{$("loginError").textContent="Adresse e-mail ou mot de passe incorrect.";}};
$("resetPassword").onclick=async()=>{const mail=$("email").value.trim();if(!mail)return $("loginError").textContent="Saisissez d’abord votre adresse e-mail.";try{await sendPasswordResetEmail(auth,mail);$("loginError").textContent="E-mail de réinitialisation envoyé.";}catch{$("loginError").textContent="Impossible d’envoyer l’e-mail.";}};
$("signupForm").onsubmit=async e=>{e.preventDefault();const button=$("signupSubmit"),messageBox=$("signupMessage");button.disabled=true;button.textContent="Envoi…";messageBox.textContent="";registrationInProgress=true;try{const credential=await createUserWithEmailAndPassword(auth,$("signupEmail").value.trim(),$("signupPassword").value);await setDoc(doc(db,"users",credential.user.uid),{firstName:$("signupFirstName").value.trim(),lastName:$("signupLastName").value.trim(),email:credential.user.email,role:"pending",createdAt:serverTimestamp()});await signOut(auth);messageBox.className="success-message";messageBox.textContent="Demande envoyée. L’AGP vous informera lorsque votre accès sera activé.";e.currentTarget.reset();}catch(error){console.error(error);messageBox.className="error";messageBox.textContent=error.code==="auth/email-already-in-use"?"Un compte existe déjà avec cette adresse.":"Impossible de créer le compte. Vérifiez les informations saisies.";}finally{registrationInProgress=false;button.disabled=false;button.textContent="Envoyer ma demande";}};
$("logoutMember").onclick=$("logoutAdmin").onclick=async()=>{await signOut(auth);route("home");};
$("openMemberSpace").onclick=()=>{route("member");loadDashboard();}; $("refreshDashboard").onclick=loadDashboard;
document.querySelectorAll("[data-member-section]").forEach(b=>b.onclick=()=>{if(!currentUser)return openLogin();route("member");loadMemberSection(b.dataset.memberSection);});
document.querySelectorAll("[data-admin-section]").forEach(b=>b.onclick=()=>selectAdmin(b.dataset.adminSection));
const importArtisansButton=document.createElement("button");importArtisansButton.id="importArtisans";importArtisansButton.textContent="Importer la liste Excel";importArtisansButton.hidden=true;$("newItem").after(importArtisansButton);
$("newItem").onclick=()=>openEditor(); importArtisansButton.onclick=importExcelArtisans; $("closeEditor").onclick=$("cancelEditor").onclick=closeEditor; $("editorForm").onsubmit=saveAdminItem;
$("adminList").onclick=handleAdminAction; $("privateResults").onclick=handleMemberAction;
$("memberUpcomingActivities").onclick=handleActivityRegistration;

onAuthStateChanged(auth, async user=>{
  if(registrationInProgress)return;
  currentUser=user; currentRole=null;
  $("requestAccess").hidden=!!user;
  if(!user){$("authButton").textContent="Se connecter";$("statusText").textContent="Association du Grand Pavois";return;}
  $("authButton").textContent="Mon espace";$("statusText").textContent=user.email;
  try{const snap=await getDoc(doc(db,"users",user.uid));if(!snap.exists()||!["member","admin"].includes(snap.data().role))throw new Error("denied");const profile=snap.data();currentRole=profile.role;$("memberTitle").textContent=`Bienvenue${profile.firstName?` ${profile.firstName}`:""}`;if(currentRole==="admin"){route("admin");selectAdmin("activities");}else{route("member");loadDashboard();}}
  catch{await signOut(auth);$("loginError").textContent="Ce compte est en attente de validation ou son accès est suspendu.";openLogin();}
});

async function getItems(section, includeHidden=false){let ref=collection(db,config[section].collection),snap;if(!includeHidden&&["classifieds","aid"].includes(section)){const [published,own]=await Promise.all([getDocs(query(ref,where("status","==","published"))),getDocs(query(ref,where("authorUid","==",currentUser.uid)))]),merged=new Map();[...published.docs,...own.docs].forEach(d=>merged.set(d.id,{id:d.id,...d.data()}));return [...merged.values()];}try{snap=section==="activities"?await getDocs(query(ref,orderBy("eventDate","asc"))):await getDocs(ref);}catch{snap=await getDocs(ref);}return snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>includeHidden||section==="activities"?includeHidden||x.published!==false:true);}
function upcoming(x){const d=asDate(x.eventDate);if(Number.isNaN(d.getTime()))return true;d.setHours(23,59,59,999);return d>=new Date();}
function activityCard(x,joined=false,variant=""){const closed=x.registrationOpen===false&&!joined;return `<article class="member-activity-card ${variant}"><div class="activity-date"><span>${escapeHtml(new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(asDate(x.eventDate)).toUpperCase())}</span><b>${escapeHtml(new Intl.DateTimeFormat("fr-FR",{day:"2-digit"}).format(asDate(x.eventDate)))}</b></div><div class="activity-body"><span class="pill">${escapeHtml(x.category||"Activité AGP")}</span><h3>${escapeHtml(x.title)}</h3><p class="activity-meta">${escapeHtml([formatDate(x.eventDate),x.time,x.location].filter(Boolean).join(" · "))}</p>${x.capacity?`<p class="activity-capacity">👥 ${escapeHtml(x.capacity)} places maximum</p>`:""}<p>${escapeHtml(x.description)}</p><button class="registration-button ${joined?"joined":""}" data-join-activity="${x.id}" ${closed?"disabled":""}>${joined?"✓ Je participe — annuler":closed?"Inscriptions closes":"Je participe"}</button></div></article>`;}
function contentCard(section,x){if(section==="artisans"){const phone=String(x.phone||"").replace(/[^+\d]/g,"");return `<article class="result artisan-card"><span class="pill">${escapeHtml(x.category||"Artisan")}</span><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.description||"")}</p>${x.phone?`<a class="artisan-phone" href="tel:${escapeHtml(phone)}">☎ ${escapeHtml(x.phone)}</a>`:""}</article>`;}if(["classifieds","aid"].includes(section)){const contact=String(x.contact||"").trim(),isEmail=contact.includes("@"),href=isEmail?`mailto:${contact}`:`tel:${contact.replace(/[^+\d]/g,"")}`,progressLabels={open:"Ouverte",in_progress:"En cours",resolved:"Résolue"},own=x.authorUid===currentUser?.uid,statusLabels={pending:"En attente de validation",refused:"Refusée"};return `<article class="result classified-card"><div class="card-pills"><span class="pill">${escapeHtml(x.category||(section==="aid"?"Entraide":"Annonce"))}</span>${section==="aid"?`<span class="progress-pill ${escapeHtml(x.progress||"open")}">${progressLabels[x.progress]||"Ouverte"}</span>`:""}${x.status!=="published"?`<span class="submission-status ${escapeHtml(x.status)}">${statusLabels[x.status]||escapeHtml(x.status)}</span>`:""}</div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description||"")}</p><small>Proposé par ${escapeHtml(x.authorName||"un adhérent")}</small>${contact?`<a class="artisan-phone" href="${escapeHtml(href)}">${isEmail?"✉":"☎"} ${escapeHtml(contact)}</a>`:""}${own?`<div class="member-owner-actions"><button data-member-edit="${x.id}" data-section="${section}">Modifier</button>${section==="aid"&&x.status==="published"&&x.progress!=="resolved"?`<button data-member-resolve="${x.id}" data-section="${section}">Marquer résolue</button>`:""}<button class="danger" data-member-delete="${x.id}" data-section="${section}">Retirer</button></div>`:""}</article>`;}const meta=[x.category,x.authorName];return `<article class="result"><span class="pill">${escapeHtml(x.category||config[section].title)}</span><h3>${escapeHtml(x.title||x.name)}</h3><p>${escapeHtml(x.description||"")}</p><small>${escapeHtml(meta.filter(Boolean).join(" · "))}</small></article>`;}
async function getMyRegistrations(){const snap=await getDocs(query(collection(db,"activityRegistrations"),where("userUid","==",currentUser.uid)));return new Set(snap.docs.map(d=>d.data().activityId));}
async function loadDashboard(){currentMemberSection=null;const box=$("memberUpcomingActivities");box.innerHTML="<div class='notice dashboard-empty'>Chargement des prochains rendez-vous…</div>";$("privateResults").innerHTML="";const [acts,aid,ads,arts,joined]=await Promise.all([getItems("activities").catch(()=>[]),getItems("aid").catch(()=>[]),getItems("classifieds").catch(()=>[]),getItems("artisans").catch(()=>[]),getMyRegistrations().catch(()=>new Set())]);const next=acts.filter(upcoming).slice(0,3);box.innerHTML=next.length?next.map((x,index)=>activityCard(x,joined.has(x.id),index===0?"featured":"secondary-activity")).join(""):"<div class='notice dashboard-empty'><b>Le prochain rendez-vous sera bientôt annoncé.</b><span>Revenez consulter cette page dans quelques jours.</span></div>";$("aidCount").textContent=aid.filter(x=>x.status==="published").length;$("classifiedsCount").textContent=ads.filter(x=>x.status==="published").length;$("artisansCount").textContent=arts.length;}
async function loadMemberSection(section){currentMemberSection=section;const out=$("privateResults");out.innerHTML="<div class='notice'>Chargement…</div>";try{const [items,joined]=await Promise.all([getItems(section),section==="activities"?getMyRegistrations():Promise.resolve(new Set())]);const add=["classifieds","aid"].includes(section)?`<button class="primary member-add" data-member-add="${section}">＋ Proposer ${section==="aid"?"une demande":"une annonce"}</button>`:"";out.innerHTML=`<div class="section-title"><div><span>ESPACE PRIVÉ</span><h2>${config[section].title}</h2></div>${add}</div>`;if(section==="artisans")return renderArtisanDirectory(out,items);if(section==="classifieds")return renderClassifiedsDirectory(out,items);if(section==="aid")return renderAidDirectory(out,items);out.innerHTML+=items.length?items.map(x=>section==="activities"?activityCard(x,joined.has(x.id)):contentCard(section,x)).join(""):"<div class='notice'>Aucun contenu publié pour le moment.</div>";}catch{out.innerHTML="<div class='notice'>Impossible de charger cette rubrique.</div>";}}

function renderArtisanDirectory(out,items){
  const artisans=[...items].sort((a,b)=>String(a.category||"").localeCompare(String(b.category||""),"fr")||String(a.name||"").localeCompare(String(b.name||""),"fr"));
  const categories=[...new Set(artisans.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fr"));
  out.innerHTML+=`<div class="artisan-tools"><label><span>Rechercher</span><input id="artisanSearch" type="search" placeholder="Nom, métier, service…" autocomplete="off"></label><label><span>Catégorie</span><select id="artisanCategory"><option value="">Toutes les catégories</option>${categories.map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join("")}</select></label><div id="artisanResultCount" class="artisan-result-count"></div></div><div id="artisanDirectory" class="artisan-directory"></div>`;
  const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const draw=()=>{const term=normalize($("artisanSearch").value.trim()),category=$("artisanCategory").value;const filtered=artisans.filter(x=>(!category||x.category===category)&&(!term||normalize([x.name,x.category,x.description,x.phone].join(" ")).includes(term)));$("artisanResultCount").textContent=`${filtered.length} contact${filtered.length>1?"s":""}`;$("artisanDirectory").innerHTML=filtered.length?filtered.map(x=>contentCard("artisans",x)).join(""):"<div class='notice'>Aucun contact ne correspond à cette recherche.</div>";};
  $("artisanSearch").oninput=draw;$("artisanCategory").onchange=draw;draw();
}

function renderClassifiedsDirectory(out,items){
  const ads=[...items].sort((a,b)=>asDate(b.createdAt)-asDate(a.createdAt));
  const categories=["Vente","Don","Recherche","Prêt"];
  out.innerHTML+=`<div class="artisan-tools"><label><span>Rechercher</span><input id="classifiedSearch" type="search" placeholder="Objet, description, adhérent…" autocomplete="off"></label><label><span>Catégorie</span><select id="classifiedCategory"><option value="">Toutes les catégories</option>${categories.map(value=>`<option value="${value}">${value}</option>`).join("")}</select></label><div id="classifiedResultCount" class="artisan-result-count"></div></div><div id="classifiedDirectory" class="artisan-directory"></div>`;
  const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const draw=()=>{const term=normalize($("classifiedSearch").value.trim()),category=$("classifiedCategory").value;const filtered=ads.filter(x=>(!category||x.category===category)&&(!term||normalize([x.title,x.description,x.authorName].join(" ")).includes(term)));$("classifiedResultCount").textContent=`${filtered.length} annonce${filtered.length>1?"s":""}`;$("classifiedDirectory").innerHTML=filtered.length?filtered.map(x=>contentCard("classifieds",x)).join(""):"<div class='notice'>Aucune annonce ne correspond à cette recherche.</div>";};
  $("classifiedSearch").oninput=draw;$("classifiedCategory").onchange=draw;draw();
}

function renderAidDirectory(out,items){
  const requests=[...items].sort((a,b)=>asDate(b.createdAt)-asDate(a.createdAt));
  out.innerHTML+=`<div class="artisan-tools"><label><span>Rechercher</span><input id="aidSearch" type="search" placeholder="Besoin, service, adhérent…" autocomplete="off"></label><label><span>État</span><select id="aidProgress"><option value="">Tous les états</option><option value="open">Ouverte</option><option value="in_progress">En cours</option><option value="resolved">Résolue</option></select></label><div id="aidResultCount" class="artisan-result-count"></div></div><div id="aidDirectory" class="artisan-directory"></div>`;
  const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const draw=()=>{const term=normalize($("aidSearch").value.trim()),progress=$("aidProgress").value;const filtered=requests.filter(x=>(!progress||(x.progress||"open")===progress)&&(!term||normalize([x.title,x.description,x.authorName,x.category].join(" ")).includes(term)));$("aidResultCount").textContent=`${filtered.length} demande${filtered.length>1?"s":""}`;$("aidDirectory").innerHTML=filtered.length?filtered.map(x=>contentCard("aid",x)).join(""):"<div class='notice'>Aucune demande ne correspond à cette recherche.</div>";};
  $("aidSearch").oninput=draw;$("aidProgress").onchange=draw;draw();
}
async function handleActivityRegistration(e){const button=e.target.closest("[data-join-activity]");if(!button)return;button.disabled=true;const activityId=button.dataset.joinActivity,registrationId=`${activityId}_${currentUser.uid}`;try{if(button.classList.contains("joined"))await deleteDoc(doc(db,"activityRegistrations",registrationId));else await setDoc(doc(db,"activityRegistrations",registrationId),{activityId,userUid:currentUser.uid,userName:$("memberTitle").textContent.replace(/^Bienvenue\s*/,"")||currentUser.email,userEmail:currentUser.email,createdAt:serverTimestamp()});if(currentMemberSection==="activities")await loadMemberSection("activities");else await loadDashboard();}catch(error){console.error(error);button.disabled=false;}}
async function handleMemberAction(e){if(e.target.closest("[data-join-activity]"))return handleActivityRegistration(e);const edit=e.target.closest("[data-member-edit]"),remove=e.target.closest("[data-member-delete]"),resolve=e.target.closest("[data-member-resolve]"),add=e.target.closest("[data-member-add]");try{if(edit){const section=edit.dataset.section,snap=await getDoc(doc(db,config[section].collection,edit.dataset.memberEdit));return openMemberProposal(section,edit.dataset.memberEdit,snap.data());}if(remove){if(remove.dataset.confirm!=="true"){remove.dataset.confirm="true";remove.textContent="Confirmer le retrait";return;}await deleteDoc(doc(db,config[remove.dataset.section].collection,remove.dataset.memberDelete));return loadMemberSection(remove.dataset.section);}if(resolve){await updateDoc(doc(db,config[resolve.dataset.section].collection,resolve.dataset.memberResolve),{progress:"resolved",updatedAt:serverTimestamp()});return loadMemberSection(resolve.dataset.section);}if(add)return openMemberProposal(add.dataset.memberAdd);}catch(error){console.error(error);$("privateResults").insertAdjacentHTML("afterbegin","<div class='notice'>L’opération a échoué.</div>");}}

function openMemberProposal(section,id=null,data={}){$("privateResults").innerHTML=`<section class="admin-panel"><div class="panel-heading"><div><span>${id?"MODIFICATION":"PROPOSITION"}</span><h2>${id?"Modifier":section==="aid"?"Nouvelle demande d’entraide":"Nouvelle annonce"}</h2></div></div><form id="memberProposal" class="content-form"><label>Titre<input name="title" maxlength="100" required value="${escapeHtml(data.title)}"></label><label>Catégorie<select name="category">${(section==="aid"?["Demande","Proposition"]:["Vente","Don","Recherche","Prêt"]).map(v=>`<option ${data.category===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Description<textarea name="description" rows="5" maxlength="1000" required>${escapeHtml(data.description)}</textarea></label><label>Votre nom<input name="authorName" maxlength="80" required value="${escapeHtml(data.authorName)}"></label><label>Téléphone ou e-mail de contact<input name="contact" maxlength="100" required placeholder="06… ou nom@exemple.fr" value="${escapeHtml(data.contact)}"></label><div class="form-actions"><button type="button" class="secondary-action" data-member-section="${section}">Annuler</button><button class="primary">${id?"Enregistrer et soumettre":"Envoyer pour validation"}</button></div></form></section>`;$("memberProposal").onsubmit=async event=>{event.preventDefault();const f=new FormData(event.currentTarget),payload={title:f.get("title").trim(),category:f.get("category"),description:f.get("description").trim(),authorName:f.get("authorName").trim(),contact:String(f.get("contact")||"").trim(),progress:section==="aid"?(data.progress||"open"):null,authorUid:currentUser.uid,status:"pending",updatedAt:serverTimestamp()};try{if(id)await updateDoc(doc(db,config[section].collection,id),payload);else{payload.createdAt=serverTimestamp();await addDoc(collection(db,config[section].collection),payload);}$("privateResults").innerHTML="<div class='notice success'>Votre proposition a été transmise à l’administration.</div>";}catch(error){console.error(error);$("privateResults").insertAdjacentHTML("afterbegin","<div class='notice'>L’envoi a échoué.</div>");}};}

const excelArtisans = [
  [2,"Administratif","CÉBÉLIEU Stéphanie","06 82 50 59 96","Propriétaire au Grand Pavois. Toutes démarches administratives et fiscales, entraide voisins. Adresse : Grand Pavois."],
  [4,"Baby Sitting","AUBERT Alice","06 71 21 54 29","Habite le Grand Pavois. 16 ans, avec expérience. Adresse : Grand Pavois."],
  [8,"Couture","Na Créa","06 65 24 58 95","Retouches. Adresse : 111 rue Jean Mermoz (n°45), 13008 Marseille."],
  [9,"Couture","Bel Air","06 15 33 77 48","Adresse : 10 rue Bel Air, 13006 Marseille."],
  [10,"Couture","KS Retouches","06 27 57 72 91","Adresse : 6 place Ernest Delibes, 13009 Marseille. Recommandé par CÉBÉLIEU Stéphanie."],
  [12,"Désinfection / nuisibles","PARIENTE Pierre","06 07 42 00 38","Adresse : 1 rue Adolphe Thiers. Recommandé par ESKENAZI Henri."],
  [14,"Électricien","DEMARESTZ Guillaume","06 12 25 74 07","Contact recommandé par l’AGP."],
  [15,"Électricien","PERETTI Damien","06 60 47 76 45","Contact recommandé par l’AGP."],
  [16,"Électricien","SABATIE Patrick","06 19 75 18 49","Contact recommandé par l’AGP."],
  [17,"Électricien","Société Efficas — Mme SOURIAUD","06 20 82 53 85","Électricité et volets électriques. Recommandé par BONNENFANT Philippe."],
  [19,"Infirmier","Laetitia","06 01 76 01 74","Adresse : 25 boulevard Édouard Herriot, 13008 Marseille."],
  [20,"Infirmier","Camille","06 73 30 79 27","Recommandé par CÉBÉLIEU Stéphanie."],
  [22,"Informatique","KSISS Alexandre","06 29 59 59 14","Propriétaire au Grand Pavois. Entraide voisins. Adresse : Grand Pavois."],
  [23,"Informatique","CAZALS Paul","07 81 91 79 62","Habitant du Grand Pavois. Entraide voisins. Adresse : Grand Pavois."],
  [24,"Informatique","LUPART Richard","07 81 43 72 98","Habitant du Grand Pavois. Entraide voisins. Adresse : Grand Pavois."],
  [26,"Jardinage / Plantes","AUBERT Maeva","06 71 21 54 29","Propriétaire au Grand Pavois. Adresse : Grand Pavois."],
  [28,"Laveur de vitres","Nad Entreprise","06 44 02 30 44","Contact recommandé par l’AGP."],
  [33,"Miroitier","Massilia Miroiterie","04 91 33 71 66","Adresse : 2 place de la Corderie, 13007 Marseille. Recommandé par ESKENAZI Henri."],
  [35,"Opticien à domicile","ALBERTINI Julie","07 66 82 70 08","Vient avec tout son matériel. Prise en charge Sécurité sociale et mutuelles. Recommandé par CÉBÉLIEU Stéphanie."],
  [37,"Ostéopathe","TRAMONI Charlotte","06 16 76 64 80","Propriétaire au Grand Pavois. Peut se déplacer à domicile. Adresse : Grand Pavois."],
  [39,"Parquetteur","JULLIEN Olivier","06 17 97 25 18","Recommandé par SALEM Rachid."],
  [42,"Peintre-Plâtrier","POLAT Isak","06 22 49 12 79","Plâtrier-peintre."],
  [43,"Peintre-Plâtrier","AYOUBOV Timour","07 51 09 09 09","Plâtrier-peintre. Adresse : Résidence Plan de Jarre, chemin de Sormiou, 13009 Marseille. SIRET : 50012631300013. Recommandé par Julien 29-2."],
  [48,"Plombier","CRISTINEL Filip","07 51 17 51 02","Adresse : 51 boulevard Jeanne d’Arc, 13005 Marseille. Préciser Grand Pavois. Recommandé par CÉBÉLIEU Stéphanie."],
  [49,"Plombier","Josselin","06 72 90 07 23","Contact recommandé par l’AGP."],
  [50,"Plombier","Cœur de plombier — M. CŒUR","06 29 38 58 32","Plomberie et carrelage. Recommandé par BONNENFANT Philippe."],
  [51,"Plombier","KOZELKO Alexis","06 48 79 17 69","Recommandé par SALEM Rachid."],
  [53,"Rénovation","France Habitat","06 50 18 00 09","Salle de bains, carrelage, plomberie et béton ciré. Site : https://www.france-habitat-marseille.fr/. Recommandé par CASTAGNE Guy."],
  [54,"Rénovation","Joseph Boghossian","07 81 41 63 22","Recommandé par MONADJEMI Ramin."],
  [56,"Réparation matériel HIFI","Dominique Attya","06 15 16 21 88","Site : https://www.clic-droit.net/. Recommandé par CASTAGNE Guy."],
  [58,"Serrurier","YB Serrurier — Yohann AZOULAY","06 31 60 81 29","Serrurerie classique et urgence 24 h/24, 7 j/7. Adresse : 47 boulevard Rabatau."],
  [61,"Sorties chiens / Gardes","LEFRILEUX Corinne","06 52 92 13 05","Propriétaire au Grand Pavois. Adresse : Grand Pavois."],
  [63,"Vitrier et climatisation","Tryba Marseille","04 20 98 13 37","Adresse : 93 boulevard Sakakini, 13005 Marseille. Site : https://www.tryba.com/. Recommandé par M. BLEYNAT."],
  [64,"Vitrier et climatisation","Le Bouquet de l’Habitat","04 91 72 10 64","Menuiserie à Marseille, service à domicile. Adresse : 131 avenue Joseph Vidal, 13008 Marseille. Site : https://www.lbdh.fr/. Recommandé par SIALELLI Jeanne."],
  [66,"Volets roulants / Stores","Répar’stores","04 28 38 49 94","Recommandé par CAZALS Paul."]
];

async function importExcelArtisans(){
  const button=importArtisansButton;button.disabled=true;button.textContent="Import en cours…";
  try{
    await Promise.all(excelArtisans.map(([row,category,name,phone,description])=>setDoc(doc(db,"artisans",`excel-${row}`),{category,name,phone,description,status:"published",source:"LISTE DES ARTISANS.xlsx",sourceRow:row,updatedAt:serverTimestamp()},{merge:true})));
    message(`${excelArtisans.length} contacts importés avec succès.`);button.textContent="Liste Excel importée";await loadAdminList();
  }catch(error){console.error(error);message("L’import a échoué.","error");button.disabled=false;button.textContent="Réessayer l’import Excel";}
}

async function selectAdmin(section){adminSection=section;editingId=null;closeEditor();$("adminSectionTitle").textContent=config[section].title;$("newItem").hidden=["classifieds","aid","users"].includes(section);importArtisansButton.hidden=section!=="artisans";document.querySelectorAll("[data-admin-section]").forEach(b=>b.classList.toggle("active-feature",b.dataset.adminSection===section));await Promise.all([loadAdminList(),updateAdminBadges()]);}

async function updateAdminBadges(){if(currentRole!=="admin")return;try{const definitions=[ ["classifieds",query(collection(db,"classifieds"),where("status","==","pending"))], ["aid",query(collection(db,"aid"),where("status","==","pending"))], ["users",query(collection(db,"users"),where("role","==","pending"))] ],results=await Promise.all(definitions.map(([,ref])=>getDocs(ref)));document.querySelectorAll(".admin-pending-badge").forEach(x=>x.remove());definitions.forEach(([section],index)=>{const count=results[index].size,button=document.querySelector(`[data-admin-section="${section}"]`);if(count&&button){const badge=document.createElement("span");badge.className="admin-pending-badge";badge.textContent=count;badge.setAttribute("aria-label",`${count} en attente`);button.appendChild(badge);}});}catch(error){console.error(error);}}
async function loadAdminList(){const out=$("adminList");out.innerHTML="<div class='admin-empty'>Chargement…</div>";try{const items=await getItems(adminSection,true);if(adminSection==="users")return renderUserAdmin(out,items);if(!items.length)return out.innerHTML="<div class='admin-empty'>Aucun élément.</div>";out.innerHTML=items.map(x=>adminRow(x)).join("");}catch(e){console.error(e);out.innerHTML="<div class='admin-empty error-text'>Impossible de charger cette rubrique.</div>";}}

function renderUserAdmin(out,items){
  const roleOrder={pending:0,member:1,admin:2,disabled:3},users=[...items].sort((a,b)=>(roleOrder[a.role]??9)-(roleOrder[b.role]??9)||String(a.lastName||a.email||"").localeCompare(String(b.lastName||b.email||""),"fr"));
  const counts=role=>users.filter(x=>x.role===role).length;
  out.innerHTML=`<div class="user-stats"><div><b>${users.length}</b><span>Total</span></div><div class="pending"><b>${counts("pending")}</b><span>En attente</span></div><div><b>${counts("member")}</b><span>Adhérents</span></div><div><b>${counts("admin")}</b><span>Administrateurs</span></div><div><b>${counts("disabled")}</b><span>Suspendus</span></div></div><div class="user-tools"><label><span>Rechercher</span><input id="userSearch" type="search" placeholder="Nom ou adresse e-mail…" autocomplete="off"></label><label><span>Statut</span><select id="userRoleFilter"><option value="">Tous les statuts</option><option value="pending">En attente</option><option value="member">Adhérents</option><option value="admin">Administrateurs</option><option value="disabled">Suspendus</option></select></label></div><div id="userDirectory" class="admin-list-inner"></div>`;
  const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const draw=()=>{const term=normalize($("userSearch").value.trim()),role=$("userRoleFilter").value;const filtered=users.filter(x=>(!role||x.role===role)&&(!term||normalize([x.firstName,x.lastName,x.email].join(" ")).includes(term)));$("userDirectory").innerHTML=filtered.length?filtered.map(x=>adminRow(x)).join(""):"<div class='admin-empty'>Aucun adhérent ne correspond à cette recherche.</div>";};
  $("userSearch").oninput=draw;$("userRoleFilter").onchange=draw;draw();
}
function adminRow(x){if(adminSection==="users"){const ownAccount=x.id===currentUser?.uid;return `<article class="admin-item"><div><span class="status ${x.role}">${escapeHtml(x.role||"pending")}</span><h3>${escapeHtml([x.firstName,x.lastName].filter(Boolean).join(" ")||x.email||"Compte")}</h3><p>${escapeHtml(x.email||"")}</p></div><div class="admin-actions">${ownAccount?'<span class="own-account">Votre compte administrateur est protégé</span>':`<button data-user-role="member" data-id="${x.id}">Activer</button><button data-user-role="admin" data-id="${x.id}">Administrateur</button><button class="danger" data-user-role="disabled" data-id="${x.id}">Suspendre</button>`}</div></article>`;}const status=adminSection==="activities"?(x.published===false?"Masqué":"Visible"):(x.status||"pending");return `<article class="admin-item"><div><span class="status ${escapeHtml(status)}">${escapeHtml(status)}</span><h3>${escapeHtml(x.title||x.name||"Sans titre")}</h3><p>${escapeHtml(adminSection==="activities"?[formatDate(x.eventDate),x.time,x.location,x.capacity?`${x.capacity} places`:"",x.registrationOpen===false?"Inscriptions closes":""].filter(Boolean).join(" · "):(x.description||x.phone||""))}</p></div><div class="admin-actions">${adminSection==="activities"?`<button data-participants="${x.id}" data-capacity="${escapeHtml(x.capacity||"")}">Participants</button>`:""}${["classifieds","aid"].includes(adminSection)&&x.status!=="published"?`<button data-publish="${x.id}">Publier</button>`:""}<button data-edit="${x.id}">Modifier</button><button class="danger" data-delete="${x.id}">Supprimer</button></div></article>`;}
async function handleAdminAction(e){const id=e.target.dataset.id||e.target.dataset.edit||e.target.dataset.delete||e.target.dataset.publish||e.target.dataset.participants;if(!id)return;try{if(e.target.dataset.participants){const snap=await getDocs(query(collection(db,"activityRegistrations"),where("activityId","==",id))),capacity=Number(e.target.dataset.capacity)||0;const target=e.target.closest("article");let list=target.querySelector(".participant-list");if(!list){list=document.createElement("div");list.className="participant-list";target.appendChild(list);}const summary=capacity?`${snap.size} / ${capacity} participant${capacity>1?"s":""}${snap.size>=capacity?" — Complet":""}`:`${snap.size} participant${snap.size>1?"s":""}`;list.innerHTML=`<b>${summary}</b>`+(snap.empty?"<span>Aucun participant inscrit.</span>":snap.docs.map(d=>`<span>${escapeHtml(d.data().userName||d.data().userEmail)}</span>`).join(""));return;}if(e.target.dataset.userRole){await updateDoc(doc(db,"users",id),{role:e.target.dataset.userRole,updatedAt:serverTimestamp()});message("Accès mis à jour.");}else if(e.target.dataset.publish){await updateDoc(doc(db,config[adminSection].collection,id),{status:"published",reviewedAt:serverTimestamp()});message("Publication validée.");}else if(e.target.dataset.delete){if(e.target.dataset.confirmDelete!=="true"){e.target.dataset.confirmDelete="true";e.target.textContent="Confirmer la suppression";e.target.classList.add("confirm-delete");return;}if(adminSection==="activities"){const registrations=await getDocs(query(collection(db,"activityRegistrations"),where("activityId","==",id)));await Promise.all(registrations.docs.map(item=>deleteDoc(item.ref)));}await deleteDoc(doc(db,config[adminSection].collection,id));message("Élément supprimé.");}else if(e.target.dataset.edit){const snap=await getDoc(doc(db,config[adminSection].collection,id));openEditor(id,snap.data());}await loadAdminList();}catch(e){console.error(e);message("L’opération a échoué.","error");}}
function fields(section,d={}){if(section==="activities")return `<label>Titre<input name="title" maxlength="100" required value="${escapeHtml(d.title)}"></label><label>Catégorie<input name="category" maxlength="60" value="${escapeHtml(d.category||"Activité AGP")}"></label><label>Description<textarea name="description" rows="5" required>${escapeHtml(d.description)}</textarea></label><div class="activity-fields"><label>Date<input name="date" type="date" required value="${inputDate(d.eventDate)}"></label><label>Horaire<input name="time" value="${escapeHtml(d.time)}"></label><label class="wide">Lieu<input name="location" value="${escapeHtml(d.location)}"></label><label>Nombre de places (facultatif)<input name="capacity" type="number" min="1" max="999" value="${escapeHtml(d.capacity)}"></label></div><label class="check-label"><input name="registrationOpen" type="checkbox" ${d.registrationOpen===false?"":"checked"}> Inscriptions ouvertes</label><label class="check-label"><input name="published" type="checkbox" ${d.published===false?"":"checked"}> Visible par les adhérents</label>`;if(section==="artisans")return `<label>Nom de l’artisan<input name="name" required value="${escapeHtml(d.name)}"></label><label>Métier / catégorie<input name="category" required value="${escapeHtml(d.category)}"></label><label>Téléphone<input name="phone" value="${escapeHtml(d.phone)}"></label><label>Description / avis AGP<textarea name="description" rows="5" required>${escapeHtml(d.description)}</textarea></label>`;return `<label>Titre<input name="title" required value="${escapeHtml(d.title)}"></label><label>Catégorie<input name="category" value="${escapeHtml(d.category)}"></label><label>Description<textarea name="description" rows="5" required>${escapeHtml(d.description)}</textarea></label>${section==="aid"?`<label>État de la demande<select name="progress"><option value="open" ${(d.progress||"open")==="open"?"selected":""}>Ouverte</option><option value="in_progress" ${d.progress==="in_progress"?"selected":""}>En cours</option><option value="resolved" ${d.progress==="resolved"?"selected":""}>Résolue</option></select></label>`:""}<label>Statut<select name="status"><option value="pending" ${d.status==="pending"?"selected":""}>En attente</option><option value="published" ${d.status==="published"?"selected":""}>Publié</option><option value="refused" ${d.status==="refused"?"selected":""}>Refusé</option></select></label>`;}
function openEditor(id=null,d={}){editingId=id;$("editorTitle").textContent=`${id?"Modifier":"Ajouter"} ${config[adminSection].singular}`;$("editorFields").innerHTML=fields(adminSection,d);$("editorPanel").hidden=false;$("editorPanel").scrollIntoView({behavior:"smooth"});}
function closeEditor(){editingId=null;$("editorPanel").hidden=true;$("editorFields").innerHTML="";}
async function saveAdminItem(e){e.preventDefault();const f=new FormData(e.currentTarget);let payload={updatedAt:serverTimestamp()};if(adminSection==="activities")payload={...payload,title:f.get("title").trim(),category:f.get("category").trim(),description:f.get("description").trim(),eventDate:Timestamp.fromDate(new Date(`${f.get("date")}T12:00:00`)),time:f.get("time").trim(),location:f.get("location").trim(),capacity:f.get("capacity")?Number(f.get("capacity")):null,registrationOpen:f.get("registrationOpen")==="on",published:f.get("published")==="on"};else if(adminSection==="artisans")payload={...payload,name:f.get("name").trim(),category:f.get("category").trim(),phone:f.get("phone").trim(),description:f.get("description").trim(),status:"published"};else payload={...payload,title:f.get("title").trim(),category:f.get("category").trim(),description:f.get("description").trim(),status:f.get("status"),...(adminSection==="aid"?{progress:f.get("progress")}:{})};try{if(editingId)await updateDoc(doc(db,config[adminSection].collection,editingId),payload);else{payload.createdAt=serverTimestamp();await addDoc(collection(db,config[adminSection].collection),payload);}closeEditor();message("Enregistrement effectué.");await loadAdminList();}catch(e){console.error(e);message("L’enregistrement a échoué.","error");}}
let installPrompt=null;
const installButton=document.createElement("button");installButton.className="install-app-button";installButton.textContent="⬇ Installer l’application";installButton.hidden=true;document.body.appendChild(installButton);
const installPanel=document.createElement("div");installPanel.className="install-panel";installPanel.hidden=true;installPanel.innerHTML='<div><button class="install-close" aria-label="Fermer">×</button><img src="assets/icon-tour-192.png" alt="La tour du Grand Pavois"><h2>Installer AGP & Vous</h2><p id="installHelp"></p></div>';document.body.appendChild(installPanel);
const isStandalone=()=>matchMedia("(display-mode: standalone)").matches||navigator.standalone===true;
const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);
if(isIos&&!isStandalone())installButton.hidden=false;
addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;if(!isStandalone())installButton.hidden=false;});
addEventListener("appinstalled",()=>{installPrompt=null;installButton.hidden=true;installPanel.hidden=true;});
installButton.onclick=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true;return;}$("installHelp").innerHTML=isIos?'Dans Safari, touchez <b>Partager</b> puis <b>Sur l’écran d’accueil</b>.':'Ouvrez le menu de votre navigateur puis choisissez <b>Installer l’application</b> ou <b>Ajouter à l’écran d’accueil</b>.';installPanel.hidden=false;};
installPanel.onclick=event=>{if(event.target===installPanel||event.target.closest(".install-close"))installPanel.hidden=true;};
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.warn));
